# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/spanky.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/spanky.proto',
  package='spanky',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10rpc/spanky.proto\x12\x06spanky\".\n\x0bSentMessage\x12\x11\n\tChannelID\x18\x01 \x01(\x04\x12\x0c\n\x04Text\x18\x03 \x01(\t\"\x1a\n\x0cSendResponse\x12\n\n\x02ID\x18\x01 \x01(\x04\"\x1e\n\x05NewPM\x12\x15\n\rPluginMgrName\x18\x01 \x01(\t\"\x1c\n\x05\x41\x63kPM\x12\x13\n\x0bPluginMgrID\x18\x01 \x01(\t\"9\n\nReqCmdList\x12\x13\n\x0bPluginMgrID\x18\x01 \x01(\t\x12\x16\n\x0e\x43mdRequestList\x18\x02 \x03(\t\"&\n\x0bRespCmdList\x12\x17\n\x0f\x43mdResponseList\x18\x01 \x03(\t\"&\n\x0fHandleEventsReq\x12\x13\n\x0bPluginMgrID\x18\x01 \x01(\t\"I\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x11\n\tauthor_id\x18\x03 \x01(\t\x12\x11\n\tserver_id\x18\x04 \x01(\t\"\xd4\x02\n\x05\x45vent\x12+\n\nevent_type\x18\x01 \x01(\x0e\x32\x17.spanky.Event.EventType\x12\x1e\n\x03msg\x18\x02 \x01(\x0b\x32\x0f.spanky.MessageH\x00\"\xf2\x01\n\tEventType\x12\x0b\n\x07message\x10\x00\x12\x10\n\x0cmessage_edit\x10\x01\x12\x0f\n\x0bmessage_del\x10\x02\x12\x08\n\x04join\x10\x03\x12\x08\n\x04part\x10\x04\x12\x0c\n\x08\x63han_del\x10\x05\x12\x0c\n\x08\x63han_add\x10\x06\x12\x0c\n\x08\x63han_upd\x10\x07\x12\x0e\n\nmember_ban\x10\x08\x12\x10\n\x0cmember_unban\x10\t\x12\x11\n\rmember_update\x10\n\x12\x10\n\x0creaction_add\x10\x0b\x12\x13\n\x0freaction_remove\x10\x0c\x12\x10\n\x0cmsg_bulk_del\x10\r\x12\t\n\x05other\x10\x63\x42\t\n\x07payload2\xf1\x01\n\x06Spanky\x12\x32\n\x10NewPluginManager\x12\r.spanky.NewPM\x1a\r.spanky.AckPM\"\x00\x12;\n\x0eSetCommandList\x12\x12.spanky.ReqCmdList\x1a\x13.spanky.RespCmdList\"\x00\x12:\n\x0bSendMessage\x12\x13.spanky.SentMessage\x1a\x14.spanky.SendResponse\"\x00\x12:\n\x0cHandleEvents\x12\x17.spanky.HandleEventsReq\x1a\r.spanky.Event\"\x00\x30\x01\x62\x06proto3'
)



_EVENT_EVENTTYPE = _descriptor.EnumDescriptor(
  name='EventType',
  full_name='spanky.Event.EventType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='message', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='message_edit', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='message_del', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='join', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='part', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='chan_del', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='chan_add', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='chan_upd', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='member_ban', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='member_unban', index=9, number=9,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='member_update', index=10, number=10,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='reaction_add', index=11, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='reaction_remove', index=12, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='msg_bulk_del', index=13, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='other', index=14, number=99,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=468,
  serialized_end=710,
)
_sym_db.RegisterEnumDescriptor(_EVENT_EVENTTYPE)


_SENTMESSAGE = _descriptor.Descriptor(
  name='SentMessage',
  full_name='spanky.SentMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ChannelID', full_name='spanky.SentMessage.ChannelID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Text', full_name='spanky.SentMessage.Text', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=74,
)


_SENDRESPONSE = _descriptor.Descriptor(
  name='SendResponse',
  full_name='spanky.SendResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='spanky.SendResponse.ID', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=102,
)


_NEWPM = _descriptor.Descriptor(
  name='NewPM',
  full_name='spanky.NewPM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PluginMgrName', full_name='spanky.NewPM.PluginMgrName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=134,
)


_ACKPM = _descriptor.Descriptor(
  name='AckPM',
  full_name='spanky.AckPM',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PluginMgrID', full_name='spanky.AckPM.PluginMgrID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=164,
)


_REQCMDLIST = _descriptor.Descriptor(
  name='ReqCmdList',
  full_name='spanky.ReqCmdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PluginMgrID', full_name='spanky.ReqCmdList.PluginMgrID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='CmdRequestList', full_name='spanky.ReqCmdList.CmdRequestList', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=223,
)


_RESPCMDLIST = _descriptor.Descriptor(
  name='RespCmdList',
  full_name='spanky.RespCmdList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='CmdResponseList', full_name='spanky.RespCmdList.CmdResponseList', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=263,
)


_HANDLEEVENTSREQ = _descriptor.Descriptor(
  name='HandleEventsReq',
  full_name='spanky.HandleEventsReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='PluginMgrID', full_name='spanky.HandleEventsReq.PluginMgrID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=265,
  serialized_end=303,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='spanky.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='spanky.Message.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='spanky.Message.id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='author_id', full_name='spanky.Message.author_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='spanky.Message.server_id', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=378,
)


_EVENT = _descriptor.Descriptor(
  name='Event',
  full_name='spanky.Event',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='event_type', full_name='spanky.Event.event_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='spanky.Event.msg', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EVENT_EVENTTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='spanky.Event.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=381,
  serialized_end=721,
)

_EVENT.fields_by_name['event_type'].enum_type = _EVENT_EVENTTYPE
_EVENT.fields_by_name['msg'].message_type = _MESSAGE
_EVENT_EVENTTYPE.containing_type = _EVENT
_EVENT.oneofs_by_name['payload'].fields.append(
  _EVENT.fields_by_name['msg'])
_EVENT.fields_by_name['msg'].containing_oneof = _EVENT.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['SentMessage'] = _SENTMESSAGE
DESCRIPTOR.message_types_by_name['SendResponse'] = _SENDRESPONSE
DESCRIPTOR.message_types_by_name['NewPM'] = _NEWPM
DESCRIPTOR.message_types_by_name['AckPM'] = _ACKPM
DESCRIPTOR.message_types_by_name['ReqCmdList'] = _REQCMDLIST
DESCRIPTOR.message_types_by_name['RespCmdList'] = _RESPCMDLIST
DESCRIPTOR.message_types_by_name['HandleEventsReq'] = _HANDLEEVENTSREQ
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Event'] = _EVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SentMessage = _reflection.GeneratedProtocolMessageType('SentMessage', (_message.Message,), {
  'DESCRIPTOR' : _SENTMESSAGE,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.SentMessage)
  })
_sym_db.RegisterMessage(SentMessage)

SendResponse = _reflection.GeneratedProtocolMessageType('SendResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDRESPONSE,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.SendResponse)
  })
_sym_db.RegisterMessage(SendResponse)

NewPM = _reflection.GeneratedProtocolMessageType('NewPM', (_message.Message,), {
  'DESCRIPTOR' : _NEWPM,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.NewPM)
  })
_sym_db.RegisterMessage(NewPM)

AckPM = _reflection.GeneratedProtocolMessageType('AckPM', (_message.Message,), {
  'DESCRIPTOR' : _ACKPM,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.AckPM)
  })
_sym_db.RegisterMessage(AckPM)

ReqCmdList = _reflection.GeneratedProtocolMessageType('ReqCmdList', (_message.Message,), {
  'DESCRIPTOR' : _REQCMDLIST,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.ReqCmdList)
  })
_sym_db.RegisterMessage(ReqCmdList)

RespCmdList = _reflection.GeneratedProtocolMessageType('RespCmdList', (_message.Message,), {
  'DESCRIPTOR' : _RESPCMDLIST,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.RespCmdList)
  })
_sym_db.RegisterMessage(RespCmdList)

HandleEventsReq = _reflection.GeneratedProtocolMessageType('HandleEventsReq', (_message.Message,), {
  'DESCRIPTOR' : _HANDLEEVENTSREQ,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.HandleEventsReq)
  })
_sym_db.RegisterMessage(HandleEventsReq)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.Message)
  })
_sym_db.RegisterMessage(Message)

Event = _reflection.GeneratedProtocolMessageType('Event', (_message.Message,), {
  'DESCRIPTOR' : _EVENT,
  '__module__' : 'rpc.spanky_pb2'
  # @@protoc_insertion_point(class_scope:spanky.Event)
  })
_sym_db.RegisterMessage(Event)



_SPANKY = _descriptor.ServiceDescriptor(
  name='Spanky',
  full_name='spanky.Spanky',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=724,
  serialized_end=965,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewPluginManager',
    full_name='spanky.Spanky.NewPluginManager',
    index=0,
    containing_service=None,
    input_type=_NEWPM,
    output_type=_ACKPM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetCommandList',
    full_name='spanky.Spanky.SetCommandList',
    index=1,
    containing_service=None,
    input_type=_REQCMDLIST,
    output_type=_RESPCMDLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendMessage',
    full_name='spanky.Spanky.SendMessage',
    index=2,
    containing_service=None,
    input_type=_SENTMESSAGE,
    output_type=_SENDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='HandleEvents',
    full_name='spanky.Spanky.HandleEvents',
    index=3,
    containing_service=None,
    input_type=_HANDLEEVENTSREQ,
    output_type=_EVENT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPANKY)

DESCRIPTOR.services_by_name['Spanky'] = _SPANKY

# @@protoc_insertion_point(module_scope)
